import forms from '@tailwindcss/forms'
import containerQueries from '@tailwindcss/container-queries'

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'outline-variant': '#80848A',
        'outline': '#8A8E94',
        'primary': '#50B152',
        'secondary-fixed': '#94fb6f',
        'primary-container': '#1a5c1c',
        'tertiary-fixed': '#ffdbcd',
        'on-secondary-fixed-variant': '#145200',
        'inverse-on-surface': '#111419',
        'on-secondary-fixed': '#042100',
        'inverse-primary': '#b5c4ff',
        'secondary': '#50B152',
        'primary-fixed-dim': '#b5c4ff',
        'on-tertiary': '#ffffff',
        'on-secondary': '#ffffff',
        'surface-container': '#45494E',
        'on-error-container': '#ffb4ab',
        'error': '#ba1a1a',
        'surface-container-low': '#0f2b66',
        'on-primary-container': '#c0f0c1',
        'on-secondary-container': '#b7f0c0',
        'surface': '#40454A',
        'on-surface-variant': '#D8DCDF',
        'tertiary': '#180400',
        'on-background': '#ffffff',
        'surface-tint': '#50B152',
        'on-primary': '#ffffff',
        'on-tertiary-container': '#bc7758',
        'on-tertiary-fixed': '#360f00',
        'inverse-surface': '#eef1f3',
        'on-primary-fixed': '#041749',
        'background': '#40454A',
        'surface-bright': '#494D51',
        'on-surface': '#ffffff',
        'on-primary-fixed-variant': '#354476',
        'on-error': '#ffffff',
        'surface-container-highest': '#55585D',
        'error-container': '#ffdad6',
        'primary-fixed': '#dce1ff',
        'tertiary-fixed-dim': '#ffb596',
        'surface-container-high': '#4D5054',
        'secondary-container': '#1f4a2d',
        'surface-container-lowest': '#373B40',
        'on-tertiary-fixed-variant': '#6e381e',
        'surface-variant': '#3B3F44',
        'tertiary-container': '#3e1300',
        'surface-dim': '#35393F',
        'secondary-fixed-dim': '#7ad27d',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [forms, containerQueries],
}
